### ISSUE TITLE
Need for naïve date/time

### ISSUE THREAD

**Issue by mikaelho** [ariebovenberg/whenever#21] opened 2024-01-31 16:51 UTC
Hello, and thank you for the [excellent article](https://dev.arie.bovenberg.net/blog/python-datetime-pitfalls/).

It raised the following question in my mind, and I would be very happy to hear your take on it, as you obviously have thought long and hard on the problem of date/times in Python.

What do you see as the must-have use case for naïve date/time, to warrant its inclusion in `whenever`?

To me, it only brings confusion, while all the potential use cases seem just as well (or better) served by UTC or local date/times.

**Comment by ariebovenberg** [comment] 2024-01-31 18:22
Hi @mikaelho, thanks for taking the time to open this issue 👋 

I must say I've often had the same thought. I welcome a thoughtful discussion on the topic 🙌 

Here is an incomplete, quick-n-dirty brain-dump of my thoughts so far:

against naive:
- `NaiveDateTime` is basically `UTCDateTime`, but with less functionality
-  it tempts users to forego considering timezones altogether
-  only having aware datetimes makes the library conceptually cleaner

for naive:
- modern datetime libraries in other languages appear to have an equivalent (Rust chrono, Javascript temporal)
- some applications can genuinely ignore timezone considerations (for example a simulation game). It's possible, but weird to force them to use `UTCDateTime` as a stand-in.
- Naive datetimes are often useful as an in-between step when ingesting data. For example, you get datetime from a csv without any timezone information. You parse this as naive, and then add timezone information later (out of band—i.e. you know the csv is in Tokyo timezone).

Another question I've mulled over: Would `PlainDateTime` be a better name for this concept? (see Javascript Temporal)

**Comment by notatallshaw** [comment] 2024-02-01 15:56
> * Naive datetimes are often useful as an in-between step when ingesting data. For example, you get datetime from a csv without any timezone information. You parse this as naive, and then add timezone information later (out of band—i.e. you know the csv is in Tokyo timezone).

A real world use case for this that is very common in work I've done is where Python is moving data from one location to another as faithfully as possible where neither location support timezone information (csv, spreadsheet, database, etc.) but you do want to validate the data is a real datetime.

Adding timezone information would neither be faithful to the data and it would introduce an extra complexity which has the chance to introduce mistakes,

**Comment by ariebovenberg** [comment] 2024-02-02 11:16
I think it's indeed clear that there should be *some way* to express a date and time without timezone information. 

I like your example @mikaelho about UTF-8 strings, but remember that raw bytes are also still allowed (`bytes`) in case you _do_ want access to the data without encoding. Continuing with this anlogy, you could say that `str = bytes + encoding` in the same way that `aware datetime = naive datetime + timezone information`. In my opinion the problem is in *naming*. Imagine if instead of `bytes`, we had `naive_str` 👀 . What would a better name for `NaiveDateTime` look like—That best distinguishes is from the 'real world' datetimes?

Some quick ideas:
- `DateTime`
- `DateAndTime`
- `WallTime`, 
- `ClockTime`
- `WallClockTIme`
- `YearMonthDayHourMinuteSecond`
- `YMDHMS`

**Comment by mikaelho** [comment] 2024-02-02 11:31
Aye, I hear you.

Conceptually, we have these:
- An exact moment of time
    - Represented by a date/time with timezone information (or a timestamp, if we have an exact point in time for 0)
- Date, as a rough idea of a period of time
    - Represented adequately, as far as I understand, by Python's `date` class, with additional support from `calendar`, maybe
- Time of day, as a conceptual idea similar to "noon", also referred to as wall time, as you say
   - Represented by `datetime.time`, as long as we do not mix it with timezones

So, I could suggest `TimeOfDay`, and `DateAndTimeOfDay`?

**Comment by metaperl** [comment] 2024-02-02 13:47
> I think it's indeed clear that there should be _some way_ to express a date and time without timezone information.
> 
>What would a better name for `NaiveDateTime` look like—That best distinguishes is from the 'real world' datetimes?
> 
> Some quick ideas:
> 
> * `DateTime`

absolutely not. This leads people to think that what they have is  actually valid as a datetime, when without timezone, they simply do not have a valid datetime instance.

> * `DateAndTime`

hmm. again the big issue that it really is not date and time because time without a timezone is not truly a time. This again tricks the average person into thinking they are doing a good job by constructing something without timezone.

> * `WallTime`,

I dont know what WallTime is, so I cant comment.

> * `ClockTime`

implicitly, the clock is in a certain timezone. So, no.

> * `WallClockTIme`

no comment. But i vote against this.

> * `YearMonthDayHourMinuteSecond`

no, because the `HMS` part of this lacks timezone.

> * `YMDHMS`

no, because the `HMS` part of this lacks timezone.

# My  quick-n-dirty brain-dump of names

* BrokenDateTime

end of brain dump. please do not cut any slack for people who want to use this. Dont allow them to think everything is hunky-dory when in fact they have broken data or a broken object that is crucially lacking information.

**Comment by metaperl** [comment] 2024-02-02 13:53
> Aye, I hear you.
> 
> Conceptually, we have these:
> 
> * An exact moment of time
>   
>   * Represented by a date/time with timezone information (or a timestamp, if we have an exact point in time for 0)
> * Date, as a rough idea of a period of time

and without timezone, this rough idea spans way more than 24 hours. I work with people in India who are 9.5 hours ahead of me... 

Your comment `rough idea of a period of time` is a good one. Because certainly `yesterday` here and in India does not mean last year in either place. 


> So, I could suggest `TimeOfDay`, and `DateAndTimeOfDay`?

I would take a strong stance and say: with no timezone, there is no `TimeOfDay`.

**Comment by notatallshaw** [comment] 2024-02-02 15:52
Another use case I see missing is "the user doesn't know", they get a datetime from some source that does not provide, or document, the timezone.

Adding a timezone, even UTC, adds false information to the object, and has the chance of introducing bugs into any calculations the user might do after that.

**Comment by aeb-dev** [comment] 2024-02-02 18:20
How about

```python
from whenever import (
    # For the "UTC everywhere" case
    DateTimeUTC,
    # Simple localization sans DST
    DateTimeOffset,
    # Full-featured IANA timezones
    DateTimeZoned,
    # The local system timezone
    DateTimeLocal,
    # Detached from any timezones
    DateTimeUnknown,
)
```

There are two things to notice here first I think the Zone information should come last as the string format also follow. Second, the `NaiveDateTime` can be `DateTimeUnknown` meaning you have a date time but its zone information is not provided/known

**Comment by mikaelho** [comment] 2024-02-03 10:41
For what it is worth, I like the consistency and logic of @aeb-dev's suggestion.

My original reason to open this issue was to understand whether there is a need for the timezone-undefined functionality at all. The answer to that question seems to be yes, in some unsavory legacy situations, we still need it.

Now, my remaining concern is how the API could communicate, either through naming or even something stronger like mandatory parameters, that the timezone-undefined option should be the last one you use, only when you really need it, and **not** the default you pick when you "do not want to think about" timezones.

Something like "timezone-undefined considered dangerous" guidance to the package user, I guess.

**Comment by ariebovenberg** [comment] 2024-02-03 21:49
> Now, my remaining concern is how the API could communicate, either through naming or even something stronger like mandatory parameters, that the timezone-undefined option should be the last one you use, only when you really need it, and not the default you pick when you "do not want to think about" timezones.

Agree that it should be discouraged to use it for the wrong reason. Note that "naive" is already a pretty negative word—no programmer wants to be naive do they? 👀 

Regarding the suggestion of `DateTimeUnknown`. I think "unknown" is a bit _too_ specific. It may be known, but simply not defined. There's a reason that languages have `null` and `undefined` constants but rarely `unknown`. `DateTimeUndefined` would be better than `Unknown`.

Also note that "Naive" has a big advantage over the other names: recognition. Even if you come up with an objectively better name, you'll still face an uphill battle convincing the entire community, that has mostly agreed that "naive" is the term for this.

I might add: the fact that `whenever.NaiveDateTime` has no `now()` method already helps a lot with discouraging its use. In the end, you only get `NaiveDateTime` if you create them—and `now()` is probably one of the most common ways.

**Comment by mikaelho** [comment] 2024-02-04 13:07
Hmm, yes, now that you use `DateTimeUnknown` or `DateTimeUnspecified` in isolation, there is a clear challenge with that naming approach - reader will think that the date/time is unknown, while the word refers to the timezone.

For discoverability, I would suggest that `NaiveDateTime` defines `now()`, but both its documentation and the exception it raises explain why it cannot be used, and what should be used instead.

**Comment by ariebovenberg** [comment] 2024-02-04 19:16
I did a small survey of how other high-level languages and standards refer to the concept of 'datetime without timezone information':

| language      | without timezone information | system timezone |
|---------------|------------------------------|-----------------|
| Python        | naive                        | local           |
| C# (NodaTime) | local                        |                 |
| Rust (chrono) | naive                        | local           |
| JS (Temporal) | local                        |                 |
| Haskell       | local                        |                 |
| Java          | local                        |                 |
| ISO8601       | local                        |                 |

It looks like `LocalDateTime` is probably the most widely accepted name. It almost looks as though Python and Rust only call it 'naive' to distinguish it from the timezone of the local system 🤔 

This is particularly interesting as in #30 I'm coming to the conclusion that the current `whenever.LocalDateTime` is not the right abstraction, and needs to be revised. Probably it will disappear and a method like `with_system_offset()` will be added to `NaiveDateTime` (which itself may be renamed).

---

> For discoverability, I would suggest that NaiveDateTime defines now(), but both its documentation and the exception it raises explain why it cannot be used, and what should be used instead.

I'd still make it invisible to the type checker at least, so you get that sweet red squiggle 🖍️

**Comment by notatallshaw** [comment] 2024-02-04 19:21
> I'd still make it invisible to the type checker at least, so you get that sweet red squiggle 🖍️

I don't understand the value in this, for the use cases it is valid it is valid, why would you want IDEs and type checkers to raise errors?

I understand making it discouraged, because it's not right for the general use case, and even less discoverable, but why actively cause pain for developers when it's the right choice for their use case?

**Comment by notatallshaw** [comment] 2024-02-04 19:30
> I might add: the fact that `whenever.NaiveDateTime` has no `now()` method already helps a lot with discouraging its use. In the end, you only get `NaiveDateTime` if you create them—and `now()` is probably one of the most common ways.

A question on this, some interfaces refuse datetimes with a timezone because the underlying data structure doesn't accept them (e.g. a library that writes to xlsx format), so if the library accepted a timezone it would have to guess on what to do (discard it, convert it to utc, local, etc.), and guessing in the face of ambiguity is discouraged.

So when a user is writing to such an interface, is there a way to turn a regular timezoned datetime into a timezoneless datetime without ambiguity?

**Comment by ariebovenberg** [comment] 2024-02-04 19:31
> I don't understand the value in this, for the use cases it is valid it is valid, why would you want IDEs and type checkers to raise errors?

> I understand making it discouraged, because it's not right for the general use case, and even less discoverable, but why actively cause pain for developers when it's the right choice for their use case?

 not sure if we're talking about the same thing 🤔 . Agree that if a user decide to work with naive datetimes, there shouldn't be any underhanded blockers.

My remark about "the red squiggle" is about the `NaiveDateTime.now()` method, which is not defined because (IMHO) it's not a valid use case. Naive is detached from the timeline, so the concept of "now" is not defined. One should do `UTCDateTime.now().naive()` or `ZonedDateTime.now("Asia/Toyko").naive()` instead.

**Comment by notatallshaw** [comment] 2024-02-04 19:34
> not sure if we're talking about the same thing 🤔 . Agree that if a user decide to work with naive datetimes, there shouldn't be any underhanded blockers.

Oh yes, I misunderstood the context, I agree you!

**Comment by ariebovenberg** [comment] 2024-02-04 19:39
@notatallshaw to be clear: my random thought (not sure if a good idea in the end 😉 ) was to define a `NaiveDateTime.now` method that helps users make sense of why it doesn't exist—i.e. you don't get 'AttributeError`, you get a slightly nicer method explaining that you cannot define the "now" of a naive datetime.

You'd have to 'hide' the method from the type checker though, since people using a type checker would probably rather see a red squiggle than a message at runtime

```python

class NaiveDateTime:
    if not TYPE_CHECKING:
        def now():
            raise AttributeError("the now() method is not define for NaiveDateTime, because blabla. See blabla for more information")
```

**Comment by ariebovenberg** [comment] 2024-02-04 19:43
> A question on this, some interfaces refuse datetimes with a timezone because the underlying data structure doesn't accept them (e.g. a library that writes to xlsx format), so if the library accepted a timezone it would have to guess on what to do (discard it, convert it to utc, local, etc.), and guessing in the face of ambiguity is discouraged.
> 
> So when a user is writing to such an interface, is there a way to turn a regular timezoned datetime into a timezoneless datetime without ambiguity?

I think the `naive()` method does this—but I'm not sure I understand completely.

Here is how I see what you describe:

```python
def save_to_database(d: NaiveDateTime):
    ...  # the database doesn't support timezone information. There is implicit agreement it should be utc

my_zoned_dt = ZonedDateTime.now('Asia/Tokyo')
save_to_database(my_zoned_dt.as_utc().naive())
```

**Comment by metaperl** [comment] 2024-02-05 01:34
Local is horribly misleading.  It makes you think that it automatically
chooses the local timezone.

**Comment by ariebovenberg** [comment] 2024-02-07 08:48
From Python's perspective it is indeed misleading. The Python `datetime` docs constantly refer to "local time" as the system local time. It's unfortunate that "local time" has a slightly other definition in other contexts 🤔 . 

I suppose `whenever` will face a lot of similar dilemmas: 

1. go with the Python definition that people as used to. Downside is that these terms may have become outdated, or contradictory with the larger software engineering community.
2. or: go with the most widely used definitions. Downside is that these may be different than Python users may expect.

Thinking down the same line, here are a few more alternatives names for `NaiveDateTime`:
- `PureDateTime` (following the example of `pathlib.Path` and `pathlib.PurePath`)
- `PlainDateTime` (following the modern Temporal)
- `BareDateTime`
- `SimpleDateTime`
- `BasicDateTime`

**Comment by bxparks** [comment] 2024-02-18 21:11
I think the worst choice is `LocalDateTime`. As far as I can tell, Joda-Time was the one of the first libraries to popularize this name, and others followed their lead, e.g. java.time, and NodaTime. As others have already said, the term "local" is confusing and misleading for this class.

The next worst choice is `NaiveDateTime`. I realize that "naive" is the term used in the Python community for the concept of a "date time without timezone or offset", but I have always disliked it. It is not self-explanatory. It forces the user to remember what "naive" means in the context of "date time" classes. It seems like an unnecessary cognitive overhead, even if minor.

Some of the other options that you listed (`BareDateTime`, `SimpleDateTime`, `BasicDateTime`) are actually pretty good. 

But the one I like the most is `PlainDateTime`. The word "plain" seems self-descriptive and appropriate. It is the _unadorned_ `DateTime` class. It is the name used by JS Temporal, and all else being equal, it's nice to go with an existing convention.

Anyway, just a drive-by comment from someone who has built a handful of date/time/timezone libraries, so I can sympathize with some of the issues faced by this project. If I could reimplement my libraries again, I would choose `PlainDateTime`.

**Comment by ariebovenberg** [comment] 2024-02-22 15:59
My take aways from reading 100+ github comments in the links above...
- Unsurprisingly, Jodatime and Nodatime authors strongly advocate for `LocalDateTime` for consistency. There were also many comments against.
- `Plain` was actually a dark horse. It didn't receive many comments in support (or against) but it won out in the final poll
- `Naive` had several comments in support, but was dropped before the final poll due to concerns over negative connotations

I'm gravitating back to `Naive` after all this reading...
- `Plain` wasn't chosen because it was particularly good itself, but because the alternatives received _way more_ criticism
- Recognizable/consistent naming is very important. Python already has 20 years of using the term `naive`. There needs to be a _really_ compelling reason to switch.

**Comment by bxparks** [comment] 2024-02-22 16:43
`NaiveDateTime` is definitely better than `LocalDateTime`. I understand that "naive" is the term used in Python. But I remember learning the `datetime` Python package for the first time, and being terribly confused about "naive" and "aware", coming from the Java world. It was probably made worse by how the standard `datetime` library blurs the line between UTC datetime and Local datetime in many places.

I figure if you are going to make a clean break from the standard `datetime` library, you might as well pick the most self-descriptive names possible. When I saw `PlainDateTime` used by Temporal, I knew immediately that I should have used that in my libraries. But I didn't know any better at the time, and it's too late for me to change my libraries now. I understand that consistent with the current Python terminology is an advantage, so I think `NaiveDateTime` is perfectly acceptable.

With regards to "exact time", I actually had not heard of this term used for "aware" datetime, so I had to go read that reference. I find that term confusing, because to me, "exact" implies precision, which is _not_ the concept captured by the `ZonedDateTime` or `OffsetDateTime` classes. In this case, I think the Python term "aware" is actually more descriptive.

I have never liked the term "civil". Does it mean "civilian" as opposed to "military"? Does it mean "related to being a citizen"? What does that have to do with a DateTime without a UTC offset?

Anyway, as the famous saying goes, naming things is a hard problem in CS. It seems to be especially hard in date/time/timezone libraries, because they need to handle so many concepts and objects.

**Comment by alejcas** [comment] 2024-02-28 14:15
> My take aways from reading 100+ github comments in the links above...
> 
> * Unsurprisingly, Jodatime and Nodatime authors strongly advocate for `LocalDateTime` for consistency. There were also many comments against.
> * `Plain` was actually a dark horse. It didn't receive many comments in support (or against) but it won out in the final poll
> * `Naive` had several comments in support, but was dropped before the final poll due to concerns over negative connotations
> 
> I'm gravitating back to `Naive` after all this reading...
> 
> * `Plain` wasn't chosen because it was particularly good itself, but because the alternatives received _way more_ criticism
> * `naive` is already established and recognized in the Python community. Recognizability is (almost) everything in a name. There needs to be a _really_ compelling reason to switch. The temporal discussions reveal no real benefits of `Plain`

I think "Naive" as a datetime without a timezone is the right choice.

**Comment by ariebovenberg** [comment] 2024-02-28 21:07
I'm going to close this issue soon with the following conclusion:

1. We need a class to represent a datetime without timezone information. A typical case is when you ingest timestamps that don't include any timezone information. 
2. The name `NaiveDateTime` is chosen for this concept:
    - this name is instantly recognizable for Python developers
    - it does a good job of describing the concept
    - the name is slightly negative, discouraging its use

**Closed** 2024-03-12 11:05 UTC
Labels: discussion

**Comment by ariebovenberg** [comment] 2025-04-19 18:37
@bxparks it's looking like you get your wish in the end. [Reflecting on early adoption](https://github.com/ariebovenberg/whenever/issues/151#issuecomment-2767074991), I'm considering "plain" to be the "least bad" option, to be changed in the next release (for the last time for real this time 😬 ).

**Comment by bxparks** [comment] 2025-04-19 20:38
@ariebovenberg: You are fortunate to do this before the API gets locked down. You are inspiring me to consider a similar change in my own libraries. Only one them is widely published, but I'm making a major version breaking change currently, so I might as well do the `PlainDateTime` change now.

(BTW, I haven't looked at your library for over a year, but congrats on your continuing progress!)
